FROM xbase

RUN sudo pacman -S --noconfirm qutebrowser intel-media-driver libvdpau-va-gl xcb-util xcb-util-cursor xcb-util-keysyms xcb-util-renderutil xcb-util-wm xcb-util-errors xcb-util-xrm

ENTRYPOINT ["/usr/bin/qutebrowser"]
